# Site info
title: Patient Way
email: jekyll@sverrirs.com
description: > # this means to ignore newlines until "baseurl:"
  Shows how the jekyll-paginate-v2 gem can be used to paginate on tags and categories together.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sverrirs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate-v2
sass:
load_paths:
    - _sass
    - node_modules
exclude:
  - Gemfile
  - Gemfile.lock
  - blog
  
# Collection configurations
collections_dir: docs
collections:
  support:
    output: true
    permalink: /:collection/:path/
  app-pwcq:
    output: true
    permalink: /:collection/:path/
  integrations:
    output: true
    permalink: /:collection/:path/
  chapters:
    output: true
    permalink: /:path
  subchapters:
    output: true
    permalink: /:path

#autopages is an optional pagination feature
autopages:
  enabled: false
  collections:
    permalink: '/:coll'
    enabled: true
    slugify:
      mode: 'ascii'
      cased: true 
  tags: 
    enabled: true
    permalink: '/:tag'

permalink: pretty

# Pagination Settings
pagination:
  enabled: true
  per_page: 100000000
  limit: 0
  sort_field: 'title'
  sort_reverse: false
  trail: 
    before: 2
    after: 2

# Navigation links
navigation: 
  - title: Home
    link: /
  - title: Support
    link: /docs/support

